if (NOT PYTHON_SUFFIX)
    message(STATUS "Using default python: -python2.7")
    SET(PYTHON_SUFFIX -python2.7)
endif()
include(q:/bdep-oss/pyside-setup-tmp/pyside_install/py2.7-qt4.8.4-64bit-release/lib/cmake/Shiboken-1.2.2/ShibokenConfig${PYTHON_SUFFIX}.cmake)
